# Load dataset

In [2]:
from sentence_transformers import SentenceTransformer
import pandas as pd

In [6]:
vietnamese_history_dataset_path = "../../datasets/vietnamese_history_dataset/data.json"
df = pd.read_json(vietnamese_history_dataset_path)
df.head()

title  ...     type
0                           BUỔI ĐẦU LỊCH SỬ NƯỚC TA  ...  chapter
1                  THỜI NGUYÊN THUỶ TRÊN ĐẤT NƯỚC TA  ...   lesson
2  Những dấu tích của Người tối cổ được tìm thấy ...  ...    title
3  Ở giai đoạn đầu, Người tinh khôn sống như thế ...  ...    title
4  Giai đoạn phát triển của Người tinh khôn có gì...  ...    title

[5 rows x 3 columns]

# gpt2

In [9]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("gpt2", cache_dir="../../tokenizer_models/")

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [12]:
text = df.iloc[0]["content"]
tokens = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

In [13]:
for k, v in tokens.items():
    print(f"{k}: {v.shape}")
    print(v)
    print()

input_ids: torch.Size([1, 35])
tensor([[ 1925,   130,   108,   130,    94,   782,    25, 20571,   157,   119,
           242,    40, 34754,   238,   157,   118,    99,    52,   406,   157,
           119,   232,  3398,   311,   157,   119,   105,   399,   130,   107,
           157,   119,   248,    34, 21664]])

attention_mask: torch.Size([1, 35])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])



In [14]:
print(tokenizer.convert_ids_to_tokens(tokens['input_ids'][0]))

['Ch', 'Æ', '°', 'Æ', '¡', 'ng', ':', 'ĠBU', 'á', '»', 'Ķ', 'I', 'ĠÄ', 'IJ', 'á', 'º', '¦', 'U', 'ĠL', 'á', '»', 'Ĭ', 'CH', 'ĠS', 'á', '»', '¬', 'ĠN', 'Æ', '¯', 'á', '»', 'ļ', 'C', 'ĠTA']


In [15]:
for token, token_id in zip(tokenizer.tokenize(text), tokenizer(text)["input_ids"][1:-1]):
    print(f"{token} -> {token_id}")

Ch -> 130
Æ -> 108
° -> 130
Æ -> 94
¡ -> 782
ng -> 25
: -> 20571
ĠBU -> 157
á -> 119
» -> 242
Ķ -> 40
I -> 34754
ĠÄ -> 238
IJ -> 157
á -> 118
º -> 99
¦ -> 52
U -> 406
ĠL -> 157
á -> 119
» -> 232
Ĭ -> 3398
CH -> 311
ĠS -> 157
á -> 119
» -> 105
¬ -> 399
ĠN -> 130
Æ -> 107
¯ -> 157
á -> 119
» -> 248
ļ -> 34


# NlpHUST/ner-vietnamese-electra-base 

In [16]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "NlpHUST/ner-vietnamese-electra-base",
    cache_dir="../../tokenizer_models/"
)

tokenizer_config.json:   0%|          | 0.00/383 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/411k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.40M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [21]:
text = df.iloc[0]["content"]
print(text)
tokens = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

Chương: BUỔI ĐẦU LỊCH SỬ NƯỚC TA


In [22]:
for k, v in tokens.items():
    print(f"{k}: {v.shape}")
    print(v)
    print()

input_ids: torch.Size([1, 10])
tensor([[    2,  1110,    42,     1,     1,     1,     1,     1, 15462,     3]])

token_type_ids: torch.Size([1, 10])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

attention_mask: torch.Size([1, 10])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])



In [23]:
print(tokenizer.convert_ids_to_tokens(tokens['input_ids'][0]))

['[CLS]', 'Chương', ':', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', 'TA', '[SEP]']


In [24]:
for token, token_id in zip(tokenizer.tokenize(text), tokenizer(text)["input_ids"][1:-1]):
    print(f"{token} -> {token_id}")

Chương -> 1110
: -> 42
[UNK] -> 1
[UNK] -> 1
[UNK] -> 1
[UNK] -> 1
[UNK] -> 1
TA -> 15462


# trituenhantaoio/bert-base-vietnamese-uncased

In [25]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained(
    "trituenhantaoio/bert-base-vietnamese-uncased",
    cache_dir="../../tokenizer_models/"
)

In [26]:
text = df.iloc[0]["content"]
print(text)
tokens = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

Chương: BUỔI ĐẦU LỊCH SỬ NƯỚC TA


In [27]:
for k, v in tokens.items():
    print(f"{k}: {v.shape}")
    print(v)
    print()

input_ids: torch.Size([1, 13])
tensor([[    2, 22360,     1,  3710,   374,    27,   881, 15780,  1460,  3086,
          3332,   389,     3]])

token_type_ids: torch.Size([1, 13])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

attention_mask: torch.Size([1, 13])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])



In [28]:
print(tokenizer.convert_ids_to_tokens(tokens['input_ids'][0]))

['[CLS]', 'chuong', '[UNK]', 'bu', '##o', '##i', 'đau', 'lich', 'su', 'nu', '##oc', 'ta', '[SEP]']


In [29]:
for token, token_id in zip(tokenizer.tokenize(text), tokenizer(text)["input_ids"][1:-1]):
    print(f"{token} -> {token_id}")

chuong -> 22360
[UNK] -> 1
bu -> 3710
##o -> 374
##i -> 27
đau -> 881
lich -> 15780
su -> 1460
nu -> 3086
##oc -> 3332
ta -> 389


# Babelscape/wikineural-multilingual-ner

In [30]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "Babelscape/wikineural-multilingual-ner",
    cache_dir="../../tokenizer_models/",
)

tokenizer_config.json:   0%|          | 0.00/333 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [31]:
text = df.iloc[0]["content"]
print(text)
tokens = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

Chương: BUỔI ĐẦU LỊCH SỬ NƯỚC TA


In [32]:
for k, v in tokens.items():
    print(f"{k}: {v.shape}")
    print(v)
    print()

input_ids: torch.Size([1, 10])
tensor([[  101, 88797,   131,   100,   100,   100,   100,   100, 91075,   102]])

token_type_ids: torch.Size([1, 10])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

attention_mask: torch.Size([1, 10])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])



In [33]:
print(tokenizer.convert_ids_to_tokens(tokens['input_ids'][0]))

['[CLS]', 'Chương', ':', '[UNK]', '[UNK]', '[UNK]', '[UNK]', '[UNK]', 'TA', '[SEP]']


In [34]:
for token, token_id in zip(tokenizer.tokenize(text), tokenizer(text)["input_ids"][1:-1]):
    print(f"{token} -> {token_id}")

Chương -> 88797
: -> 131
[UNK] -> 100
[UNK] -> 100
[UNK] -> 100
[UNK] -> 100
[UNK] -> 100
TA -> 91075


# Summary

Để so sánh **hiệu quả tokenization** giữa các tokenizer/model khác nhau, có thể dùng một số **chỉ số định lượng và định tính** :


### 🧮 **1. Chỉ số định lượng (Quantitative Metrics)**

#### ✅ **a. Trung bình số tokens / mẫu**

* **Mục đích**: Đánh giá độ “nén” của tokenizer (ít tokens hơn cho cùng nội dung → tốt hơn).
* **Công thức**:

  $$
  \text{Avg. tokens per sample} = \frac{\sum_{i=1}^{N} \text{len(tokens}_i\text{)}}{N}
  $$

#### ✅ **b. Tỷ lệ “subword splitting”**

* **Mục đích**: Tokenizer tốt sẽ ít phải cắt từ tiếng Việt thành nhiều mảnh.
* **Công thức**:

  $$
  \text{Subword ratio} = \frac{\text{Tổng số subwords}}{\text{Tổng số từ gốc}}
  $$

#### ✅ **c. Vocabulary coverage (nếu có từ điển chuẩn)**

* **Mục đích**: Đo mức độ bao phủ từ vựng tiếng Việt thực tế.
* So với từ điển chuẩn hoặc tập wordlist corpus.
* **Chỉ số**:

  * % từ vựng có trong vocab
  * % từ vựng bị tách thành subwords

#### ✅ **d. Tỷ lệ token đặc biệt / padding**

* Xem tokenizer có sinh nhiều `[PAD]`, `[UNK]` không (dấu hiệu thiếu hiệu quả).


### 📊 **2. Chỉ số định tính (Qualitative Analysis)**

#### 🔍 **a. Các ví dụ token hóa thực tế**

* So sánh cách tokenizer xử lý các câu tiếng Việt có:

  * từ ghép
  * dấu tiếng Việt (dấu hỏi, ngã, sắc…)
  * từ mượn, từ chuyên ngành
  * câu ngắn/dài, chính tả không chuẩn

#### 🎯 **b. Độ nguyên vẹn từ vựng**

* Tokenizer tốt nên giữ được từ đơn/từ ghép tiếng Việt như `"học sinh"`, `"giáo viên"` thay vì `"học", "##sinh"`


### ⚙️ **3. Thực nghiệm phụ trợ (nếu cần mở rộng)**

* Thử huấn luyện nhanh 1 downstream task như classification (sentiment, intent, etc.) với từng tokenizer → so sánh F1/accuracy để xem ảnh hưởng thực tế.
* Đo thời gian tokenize + memory usage nếu đánh giá hiệu suất.


### 📑 Gợi ý trình bày báo cáo

| Mô hình   | Avg Tokens | Subword Ratio | % OOV | Ví dụ token hóa                        |
| --------- | ---------- | ------------- | ----- | -------------------------------------- |
| BERT Pho  | 54.3       | 1.21          | 2.3%  | "giáo viên" → `['giáo', 'viên']`       |
| GPT2-ViT5 | 48.6       | 1.09          | 1.1%  | "giáo viên" → `['giáo viên']`          |
| mBERT     | 61.2       | 1.35          | 3.7%  | "giáo viên" → `['gi', '##áo', 'viên']` |
